Show full Repo Description
Iamlooker/Droid-ify pull request #227
Opened 2023-02-03 05:42 UTC by skyGtm

Repository description is usually unreadable, because the sentence is incomplete. so this commit will show repo description upto 10 lines, even if the description exceeds more than 10 lines, the sentence will be more readable than before

2023-02-03 06:55 UTC, Iamlooker commented
I will have to check how this looks

2023-02-03 08:59 UTC, Iamlooker requested changes
I will merge as soon as the requested points are matched :)

2023-02-03 08:59 UTC, Iamlooker commented on app/src/main/res/layout/repository_item.xml
> +        android:maxLines="10"
max lines of 2 looks very consistent and decent, I would rather prefer that.

2023-02-03 08:59 UTC, Iamlooker commented on app/src/main/res/layout/repository_item.xml
>          app:layout_constraintBottom_toBottomOf="parent"
Also I would like if you could add an ellipsize at the end

2023-02-03 18:20 UTC, skyGtm commented
Changes: default value of singleLine property is false so it is removed.

with maxLines 2 and ellipsize at end, text is readable but still incomplete.
Using collapsable view will be good solution if the user ever wanted to read full description.

## Full Screenshot (Click Here)
<details><summary>CLICK ME</summary>
<p>
![full_shot](https://user-images.githubusercontent.com/50160188/216677170-263714ef-f1c7-4475-b3ff-d239159816a8.jpg)
</p>
</details>

2023-02-04 06:42 UTC, Iamlooker commented
Actually you can long click to the repository to see more details

2023-02-04 06:42 UTC, Iamlooker commented
I am planning to change some ui

2023-02-04 20:06 UTC, merged